use crate::ai::claude::ClaudeClient;
use crate::ai::openai::OpenAiClient;
use crate::ai::runtime;
use crate::ai::types::*;
use crate::commands::review_commands::{NewCard, add_review_cards_internal};
use serde::{Deserialize, Serialize};
use tauri::AppHandle;
use std::sync::Mutex;
use std::path::Path;

const SESSION_FILE: &str = ".app_session.json";

/// Conversation state held in Tauri's managed state
pub struct ConversationState {
    pub messages: Mutex<Vec<Message>>,
    pub system_prompt: Mutex<String>,
    pub workspace_path: Mutex<String>,
    pub provider: Mutex<String>,
    pub model: Mutex<String>,
    /// Lesson brief generated by Prep Phase (multi-agent)
    pub lesson_brief: Mutex<Option<String>>,
    /// Teaching-specific system prompt (loaded from split config files)
    pub teaching_prompt: Mutex<String>,
    /// Practice-specific system prompt
    pub practice_prompt: Mutex<String>,
    /// Meta Prompt system prompt (for workspace generation flow)
    pub meta_prompt_prompt: Mutex<String>,
}

impl Default for ConversationState {
    fn default() -> Self {
        Self {
            messages: Mutex::new(Vec::new()),
            system_prompt: Mutex::new(String::new()),
            workspace_path: Mutex::new(String::new()),
            provider: Mutex::new("anthropic".to_string()),
            model: Mutex::new(String::new()),
            lesson_brief: Mutex::new(None),
            teaching_prompt: Mutex::new(String::new()),
            practice_prompt: Mutex::new(String::new()),
            meta_prompt_prompt: Mutex::new(String::new()),
        }
    }
}

/// Serializable session state for persistence
#[derive(Serialize, Deserialize)]
struct SavedSession {
    messages: Vec<Message>,
    system_prompt: String,
    provider: String,
    #[serde(default)]
    model: String,
}

fn save_session_to_file(workspace_path: &str, session: &SavedSession) -> Result<(), String> {
    if workspace_path.is_empty() {
        return Ok(());
    }
    let path = Path::new(workspace_path).join(SESSION_FILE);
    let json = serde_json::to_string(session).map_err(|e| format!("Serialize error: {}", e))?;
    std::fs::write(&path, json).map_err(|e| format!("Write error: {}", e))?;
    Ok(())
}

fn load_session_from_file(workspace_path: &str) -> Option<SavedSession> {
    let path = Path::new(workspace_path).join(SESSION_FILE);
    let json = std::fs::read_to_string(&path).ok()?;
    serde_json::from_str(&json).ok()
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StartSessionPayload {
    pub workspace_path: String,
    pub system_prompt: String,
    #[serde(default = "default_provider")]
    pub provider: String,
    #[serde(default)]
    pub model: String,
}

fn default_provider() -> String {
    "anthropic".to_string()
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SendMessagePayload {
    pub text: String,
    pub api_key: String,
}

/// Start a new AI session — set system prompt, workspace, and provider; clear history
#[tauri::command]
pub fn start_ai_session(
    state: tauri::State<'_, ConversationState>,
    payload: StartSessionPayload,
) -> Result<(), String> {
    let mut messages = state.messages.lock().map_err(|e| e.to_string())?;
    let mut system_prompt = state.system_prompt.lock().map_err(|e| e.to_string())?;
    let mut workspace_path = state.workspace_path.lock().map_err(|e| e.to_string())?;
    let mut provider = state.provider.lock().map_err(|e| e.to_string())?;
    let mut model = state.model.lock().map_err(|e| e.to_string())?;

    messages.clear();
    *system_prompt = payload.system_prompt;
    *workspace_path = payload.workspace_path;
    *provider = payload.provider;
    *model = payload.model;

    Ok(())
}

/// Send a user message and run the agent loop.
/// The AI response (including tool calls) is streamed via Tauri events.
#[tauri::command]
pub async fn send_chat_message(
    app: AppHandle,
    state: tauri::State<'_, ConversationState>,
    payload: SendMessagePayload,
) -> Result<(), String> {
    let system_prompt = state
        .system_prompt
        .lock()
        .map_err(|e| e.to_string())?
        .clone();
    let workspace_path = state
        .workspace_path
        .lock()
        .map_err(|e| e.to_string())?
        .clone();
    let provider = state
        .provider
        .lock()
        .map_err(|e| e.to_string())?
        .clone();
    let model = state.model.lock().map_err(|e| e.to_string())?.clone();

    // Add user message
    let user_msg = Message {
        role: "user".to_string(),
        content: vec![ContentBlock::Text {
            text: payload.text.clone(),
        }],
    };

    // Clone messages + add user message locally (don't mutate shared state yet)
    let current_messages = {
        let messages = state.messages.lock().map_err(|e| e.to_string())?;
        let mut msgs = messages.clone();
        msgs.push(user_msg);
        msgs
    };

    // Run agent loop (this may involve multiple API calls if tool_use)
    let result = runtime::run_agent_turn(
        &app,
        &payload.api_key,
        &provider,
        &model,
        &workspace_path,
        &system_prompt,
        current_messages,
    )
    .await;

    match result {
        Ok(updated_messages) => {
            // Update conversation state with full history
            let mut messages = state.messages.lock().map_err(|e| e.to_string())?;
            *messages = updated_messages;

            // Persist session to file (non-fatal if it fails)
            let _ = save_session_to_file(
                &workspace_path,
                &SavedSession {
                    messages: messages.clone(),
                    system_prompt: system_prompt.clone(),
                    provider: provider.clone(),
                    model: model.clone(),
                },
            );

            Ok(())
        }
        Err(e) => {
            // Emit error event so frontend can recover
            use tauri::Emitter;
            let _ = app.emit("agent-event", crate::ai::types::AgentEvent::Error {
                message: e.clone(),
            });
            let _ = app.emit("agent-event", crate::ai::types::AgentEvent::TurnComplete);
            Err(e)
        }
    }
}

/// Get current conversation history (for debugging / persistence)
#[tauri::command]
pub fn get_conversation_history(
    state: tauri::State<'_, ConversationState>,
) -> Result<Vec<Message>, String> {
    let messages = state.messages.lock().map_err(|e| e.to_string())?;
    Ok(messages.clone())
}

/// Check if a saved session exists for the given workspace
#[tauri::command]
pub fn has_saved_session(workspace_path: String) -> bool {
    let path = Path::new(&workspace_path).join(SESSION_FILE);
    path.exists()
}

/// Restore a saved session from the workspace file
#[tauri::command]
pub fn restore_ai_session(
    state: tauri::State<'_, ConversationState>,
    workspace_path: String,
) -> Result<usize, String> {
    let saved = load_session_from_file(&workspace_path)
        .ok_or("No saved session found")?;

    let mut messages = state.messages.lock().map_err(|e| e.to_string())?;
    let mut sp = state.system_prompt.lock().map_err(|e| e.to_string())?;
    let mut wp = state.workspace_path.lock().map_err(|e| e.to_string())?;
    let mut pv = state.provider.lock().map_err(|e| e.to_string())?;

    let count = saved.messages.len();
    *messages = saved.messages;
    *sp = saved.system_prompt;
    *wp = workspace_path;
    *pv = saved.provider;

    Ok(count)
}

/// Clear the saved session file for a workspace
#[tauri::command]
pub fn clear_saved_session(workspace_path: String) -> Result<(), String> {
    let path = Path::new(&workspace_path).join(SESSION_FILE);
    if path.exists() {
        std::fs::remove_file(&path).map_err(|e| format!("Delete error: {}", e))?;
    }
    Ok(())
}

// ─── Multi-Agent Phase Commands ───────────────────────────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PrepPhasePayload {
    pub api_key: String,
    /// Optional: system prompt override for prep agent
    pub system_prompt: Option<String>,
}

/// Phase 1: Run the Prep Agent to generate a lesson brief.
/// Must be called after start_ai_session. Stores the lesson_brief in state.
#[tauri::command]
pub async fn run_prep_phase(
    app: AppHandle,
    state: tauri::State<'_, ConversationState>,
    payload: PrepPhasePayload,
) -> Result<String, String> {
    let workspace_path = state.workspace_path.lock().map_err(|e| e.to_string())?.clone();
    let provider = state.provider.lock().map_err(|e| e.to_string())?.clone();
    let model = state.model.lock().map_err(|e| e.to_string())?.clone();

    let system_prompt = match payload.system_prompt {
        Some(ref p) if !p.is_empty() => p.clone(),
        _ => state.system_prompt.lock().map_err(|e| e.to_string())?.clone(),
    };

    let initial_message = "请按照课前准备流程，读取 workspace 文件并生成 lesson_brief。".to_string();

    let (brief, _prep_messages) = runtime::run_prep_phase(
        &app,
        &payload.api_key,
        &provider,
        &model,
        &workspace_path,
        &system_prompt,
        &initial_message,
    ).await?;

    // Store lesson_brief in state
    {
        let mut lb = state.lesson_brief.lock().map_err(|e| e.to_string())?;
        *lb = Some(brief.clone());
    }

    Ok(brief)
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TeachingPayload {
    pub text: String,
    pub api_key: String,
    /// Optional: teaching-specific system prompt
    pub teaching_prompt: Option<String>,
}

/// Phase 2: Send a student message to the Teaching Agent.
/// Uses the lesson_brief from Prep Phase. Falls back to legacy if no brief.
#[tauri::command]
pub async fn send_teaching_message(
    app: AppHandle,
    state: tauri::State<'_, ConversationState>,
    payload: TeachingPayload,
) -> Result<(), String> {
    let workspace_path = state.workspace_path.lock().map_err(|e| e.to_string())?.clone();
    let provider = state.provider.lock().map_err(|e| e.to_string())?.clone();
    let model = state.model.lock().map_err(|e| e.to_string())?.clone();
    let lesson_brief = state.lesson_brief.lock().map_err(|e| e.to_string())?.clone();

    // Use teaching-specific prompt or fall back to session prompt
    let system_prompt = match payload.teaching_prompt {
        Some(ref p) if !p.is_empty() => p.clone(),
        _ => {
            let tp = state.teaching_prompt.lock().map_err(|e| e.to_string())?.clone();
            if tp.is_empty() {
                state.system_prompt.lock().map_err(|e| e.to_string())?.clone()
            } else {
                tp
            }
        }
    };

    // Add user message, with periodic Iron Law reminder injection
    let current_messages = {
        let messages = state.messages.lock().map_err(|e| e.to_string())?;
        let message_count = messages.len();

        // Every 10 messages (~5 teaching turns), inject a hidden reminder
        // to reinforce the Three Iron Laws (combats long-context drift)
        let user_text = if message_count > 0 && message_count % 10 == 0 {
            format!(
                "[SYSTEM REMINDER — not visible to student, for your internal calibration only]\n\
                三铁律自检：\n\
                □ 只问不说：你上一条回复有\"解释\"吗？问句 ≥ 陈述句了吗？\n\
                □ 眼睛看学生：你的问题是从学生上一句话长出来的吗？盲测C通过了吗？\n\
                □ 答案是学生的：你有没有替学生总结、命名、下结论？\n\
                □ 最后一英里：学生接近答案时，追问\"你怎么理解这个词？\"而非确认。\n\
                现在回到学生的消息：\n\n{}",
                payload.text
            )
        } else {
            payload.text.clone()
        };

        let user_msg = Message {
            role: "user".to_string(),
            content: vec![ContentBlock::Text { text: user_text }],
        };

        let mut msgs = messages.clone();
        msgs.push(user_msg);
        msgs
    };

    // If we have a lesson_brief, use the new teaching turn; otherwise fall back to legacy
    let result = if let Some(ref brief) = lesson_brief {
        runtime::run_teaching_turn(
            &app,
            &payload.api_key,
            &provider,
            &model,
            &workspace_path,
            &system_prompt,
            brief,
            current_messages,
        ).await
    } else {
        println!("[Warning] No lesson_brief — falling back to legacy agent turn");
        runtime::run_agent_turn(
            &app,
            &payload.api_key,
            &provider,
            &model,
            &workspace_path,
            &system_prompt,
            current_messages,
        ).await
    };

    match result {
        Ok(updated_messages) => {
            let mut messages = state.messages.lock().map_err(|e| e.to_string())?;
            *messages = updated_messages;

            // Persist session
            let _ = save_session_to_file(
                &workspace_path,
                &SavedSession {
                    messages: messages.clone(),
                    system_prompt: system_prompt.clone(),
                    provider: provider.clone(),
                    model: model.clone(),
                },
            );

            Ok(())
        }
        Err(e) => {
            use tauri::Emitter;
            let _ = app.emit("agent-event", crate::ai::types::AgentEvent::Error {
                message: e.clone(),
            });
            let _ = app.emit("agent-event", crate::ai::types::AgentEvent::TurnComplete);
            Err(e)
        }
    }
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostLessonPayload {
    pub api_key: String,
    /// Summary of the lesson conversation for the post-lesson agent
    pub conversation_summary: Option<String>,
    /// Optional: system prompt override for post-lesson agent
    pub system_prompt: Option<String>,
}

/// Phase 3: Run the Post-Lesson Agent to update runtime files.
#[tauri::command]
pub async fn run_post_lesson(
    app: AppHandle,
    state: tauri::State<'_, ConversationState>,
    payload: PostLessonPayload,
) -> Result<(), String> {
    let workspace_path = state.workspace_path.lock().map_err(|e| e.to_string())?.clone();
    let provider = state.provider.lock().map_err(|e| e.to_string())?.clone();
    let model = state.model.lock().map_err(|e| e.to_string())?.clone();

    let system_prompt = match payload.system_prompt {
        Some(ref p) if !p.is_empty() => p.clone(),
        _ => state.system_prompt.lock().map_err(|e| e.to_string())?.clone(),
    };

    // Generate conversation summary from message history if not provided
    let summary = match payload.conversation_summary {
        Some(ref s) if !s.is_empty() => s.clone(),
        _ => {
            let messages = state.messages.lock().map_err(|e| e.to_string())?;
            generate_conversation_summary(&messages)
        }
    };

    let _ = runtime::run_post_lesson(
        &app,
        &payload.api_key,
        &provider,
        &model,
        &workspace_path,
        &system_prompt,
        &summary,
    ).await?;

    // After run_post_lesson completes, auto-generate review cards
    let card_count = auto_generate_review_cards(
        &payload.api_key, &provider, &model, &workspace_path, &summary
    ).await.unwrap_or(0);

    // Emit event to frontend
    {
        use tauri::Emitter;
        let _ = app.emit("review-cards-generated", serde_json::json!({ "count": card_count }));
    }

    Ok(())
}

/// Auto-generate review cards from the conversation summary using AI.
async fn auto_generate_review_cards(
    api_key: &str,
    provider: &str,
    model: &str,
    workspace_path: &str,
    conversation_summary: &str,
) -> Result<usize, String> {
    let system_prompt = "你是一个教学助手。根据以下课堂对话记录，生成 3-5 张间隔复习卡片。\n\n\
        要求：\n\
        1. 提取本课的核心知识点\n\
        2. 每张卡片的正面是一个具体的问题，背面是简明扼要的答案\n\
        3. card_type: \"concept\" 用于概念理解题，\"compute\" 用于计算/推导题\n\
        4. 输出严格 JSON 格式，不要额外文字\n\n\
        输出格式：\n\
        [\n  {\n    \"knowledge_point\": \"知识点名称\",\n    \"source_chapter\": \"章节\",\n    \
        \"card_type\": \"concept\",\n    \"front\": \"问题...\",\n    \"back\": \"答案...\"\n  }\n]";

    let user_message = format!("课堂对话记录：\n{}", conversation_summary);
    let messages = vec![Message {
        role: "user".to_string(),
        content: vec![ContentBlock::Text { text: user_message }],
    }];

    let response = runtime::call_ai_simple(api_key, provider, model, system_prompt, messages).await?;

    // Extract JSON array from response (handle possible markdown code fences)
    let json_str = extract_json_array(&response).ok_or("AI 返回格式不是有效的 JSON 数组")?;

    let cards: Vec<NewCard> = serde_json::from_str(&json_str)
        .map_err(|e| format!("解析复习卡片 JSON 失败: {}", e))?;

    if cards.is_empty() {
        return Ok(0);
    }

    add_review_cards_internal(workspace_path, cards)
}

/// Extract a JSON array from text that may contain markdown code fences.
fn extract_json_array(text: &str) -> Option<String> {
    let trimmed = text.trim();

    // Try direct parse first
    if trimmed.starts_with('[') {
        if let Ok(_) = serde_json::from_str::<Vec<serde_json::Value>>(trimmed) {
            return Some(trimmed.to_string());
        }
    }

    // Try extracting from markdown code fences
    if let Some(start) = trimmed.find('[') {
        if let Some(end) = trimmed.rfind(']') {
            let candidate = &trimmed[start..=end];
            if serde_json::from_str::<Vec<serde_json::Value>>(candidate).is_ok() {
                return Some(candidate.to_string());
            }
        }
    }

    None
}

/// Set the teaching-specific system prompt (loaded from split config files)
#[tauri::command]
pub fn set_teaching_prompt(
    state: tauri::State<'_, ConversationState>,
    prompt: String,
) -> Result<(), String> {
    let mut tp = state.teaching_prompt.lock().map_err(|e| e.to_string())?;
    *tp = prompt;
    Ok(())
}

// ─── Practice Mode Commands ───────────────────────────────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PracticePayload {
    pub text: String,
    pub api_key: String,
}

/// Practice Mode: Send a student message (problem/question) for Socratic guidance.
/// Unlike teaching mode, no lesson_brief is needed — the AI can read_file directly.
#[tauri::command]
pub async fn send_practice_message(
    app: AppHandle,
    state: tauri::State<'_, ConversationState>,
    payload: PracticePayload,
) -> Result<(), String> {
    let workspace_path = state.workspace_path.lock().map_err(|e| e.to_string())?.clone();
    let provider = state.provider.lock().map_err(|e| e.to_string())?.clone();
    let model = state.model.lock().map_err(|e| e.to_string())?.clone();
    let system_prompt = {
        let pp = state.practice_prompt.lock().map_err(|e| e.to_string())?.clone();
        if pp.is_empty() {
            state.system_prompt.lock().map_err(|e| e.to_string())?.clone()
        } else {
            pp
        }
    };

    let user_msg = Message {
        role: "user".to_string(),
        content: vec![ContentBlock::Text {
            text: payload.text.clone(),
        }],
    };

    let current_messages = {
        let messages = state.messages.lock().map_err(|e| e.to_string())?;
        let mut msgs = messages.clone();
        msgs.push(user_msg);
        msgs
    };

    let result = runtime::run_practice_turn(
        &app,
        &payload.api_key,
        &provider,
        &model,
        &workspace_path,
        &system_prompt,
        current_messages,
    ).await;

    match result {
        Ok(updated_messages) => {
            let mut messages = state.messages.lock().map_err(|e| e.to_string())?;
            *messages = updated_messages;

            // Persist session
            let _ = save_session_to_file(
                &workspace_path,
                &SavedSession {
                    messages: messages.clone(),
                    system_prompt: system_prompt.clone(),
                    provider: provider.clone(),
                    model: model.clone(),
                },
            );

            Ok(())
        }
        Err(e) => {
            use tauri::Emitter;
            let _ = app.emit("agent-event", crate::ai::types::AgentEvent::Error {
                message: e.clone(),
            });
            let _ = app.emit("agent-event", crate::ai::types::AgentEvent::TurnComplete);
            Err(e)
        }
    }
}

/// Set the practice-specific system prompt
#[tauri::command]
pub fn set_practice_prompt(
    state: tauri::State<'_, ConversationState>,
    prompt: String,
) -> Result<(), String> {
    let mut pp = state.practice_prompt.lock().map_err(|e| e.to_string())?;
    *pp = prompt;
    Ok(())
}

// ─── Meta Prompt Commands ─────────────────────────────────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MetaPromptPayload {
    pub text: String,
    pub api_key: String,
}

/// Meta Prompt Mode: Send a user message during the teaching system creation flow.
/// The AI guides the user through 6 phases of designing and generating a complete workspace.
#[tauri::command]
pub async fn send_meta_prompt_message(
    app: AppHandle,
    state: tauri::State<'_, ConversationState>,
    payload: MetaPromptPayload,
) -> Result<(), String> {
    let workspace_path = state.workspace_path.lock().map_err(|e| e.to_string())?.clone();
    let provider = state.provider.lock().map_err(|e| e.to_string())?.clone();
    let model = state.model.lock().map_err(|e| e.to_string())?.clone();

    // Use meta prompt system prompt, fall back to embedded content
    let system_prompt = {
        let mp = state.meta_prompt_prompt.lock().map_err(|e| e.to_string())?.clone();
        if mp.is_empty() {
            runtime::get_meta_prompt_content().to_string()
        } else {
            mp
        }
    };

    let user_msg = Message {
        role: "user".to_string(),
        content: vec![ContentBlock::Text {
            text: payload.text.clone(),
        }],
    };

    let current_messages = {
        let messages = state.messages.lock().map_err(|e| e.to_string())?;
        let mut msgs = messages.clone();
        msgs.push(user_msg);
        msgs
    };

    let result = runtime::run_meta_prompt_turn(
        &app,
        &payload.api_key,
        &provider,
        &model,
        &workspace_path,
        &system_prompt,
        current_messages,
    ).await;

    match result {
        Ok(updated_messages) => {
            let mut messages = state.messages.lock().map_err(|e| e.to_string())?;
            *messages = updated_messages;

            // Persist session
            let _ = save_session_to_file(
                &workspace_path,
                &SavedSession {
                    messages: messages.clone(),
                    system_prompt: system_prompt.clone(),
                    provider: provider.clone(),
                    model: model.clone(),
                },
            );

            Ok(())
        }
        Err(e) => {
            use tauri::Emitter;
            let _ = app.emit("agent-event", crate::ai::types::AgentEvent::Error {
                message: e.clone(),
            });
            let _ = app.emit("agent-event", crate::ai::types::AgentEvent::TurnComplete);
            Err(e)
        }
    }
}

/// Set the meta prompt system prompt
#[tauri::command]
pub fn set_meta_prompt_prompt(
    state: tauri::State<'_, ConversationState>,
    prompt: String,
) -> Result<(), String> {
    let mut mp = state.meta_prompt_prompt.lock().map_err(|e| e.to_string())?;
    *mp = prompt;
    Ok(())
}

/// Get the embedded META_PROMPT.md content
#[tauri::command]
pub fn get_meta_prompt_content() -> String {
    runtime::get_meta_prompt_content().to_string()
}

// ─── Note Generation Commands ─────────────────────────────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateNotesPayload {
    pub api_key: String,
}

/// Generate structured review notes from the current conversation.
/// Returns the notes as a Markdown string.
#[tauri::command]
pub async fn generate_lesson_notes(
    state: tauri::State<'_, ConversationState>,
    payload: GenerateNotesPayload,
) -> Result<String, String> {
    let provider = state.provider.lock().map_err(|e| e.to_string())?.clone();
    let model = state.model.lock().map_err(|e| e.to_string())?.clone();
    let messages = state.messages.lock().map_err(|e| e.to_string())?.clone();

    if messages.is_empty() {
        return Err("没有对话记录可以生成笔记".to_string());
    }

    runtime::generate_notes(&payload.api_key, &provider, &model, &messages).await
}

/// Generate Anki flashcards from the current conversation.
/// Returns TSV string (front\tback\ttags per line).
#[tauri::command]
pub async fn generate_anki_cards(
    state: tauri::State<'_, ConversationState>,
    payload: GenerateNotesPayload,
) -> Result<String, String> {
    let provider = state.provider.lock().map_err(|e| e.to_string())?.clone();
    let model = state.model.lock().map_err(|e| e.to_string())?.clone();
    let messages = state.messages.lock().map_err(|e| e.to_string())?.clone();

    if messages.is_empty() {
        return Err("没有对话记录可以生成 Anki 卡片".to_string());
    }

    runtime::generate_anki_cards(&payload.api_key, &provider, &model, &messages).await
}

/// Generate a summary from conversation messages for the post-lesson agent
fn generate_conversation_summary(messages: &[Message]) -> String {
    let mut summary = String::from("=== 课堂对话记录 ===\n\n");
    for msg in messages {
        let role_label = match msg.role.as_str() {
            "user" => "学生",
            "assistant" => "老师(内部)",
            _ => &msg.role,
        };
        for block in &msg.content {
            match block {
                ContentBlock::Text { text } => {
                    if !text.trim().is_empty() {
                        summary.push_str(&format!("[{}] {}\n\n", role_label, text.chars().take(500).collect::<String>()));
                    }
                }
                ContentBlock::ToolUse { name, input, .. } => {
                    if name == "respond_to_student" {
                        if let Some(content) = input["content"].as_str() {
                            summary.push_str(&format!("[老师→学生] {}\n\n", content));
                        }
                    }
                }
                ContentBlock::ToolResult { content, .. } => {
                    // Skip tool results in summary
                    let _ = content;
                }
                ContentBlock::Image { .. } => {
                    // Skip images in summary
                }
            }
        }
    }
    summary
}

// ─── Stateless simple chat (for world-building, etc.) ───────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SimpleChatMessage {
    pub role: String,
    pub text: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SimpleChatPayload {
    pub system_prompt: String,
    pub messages: Vec<SimpleChatMessage>,
    pub provider: String,
    pub model: String,
    pub api_key: String,
}

/// Stateless non-streaming chat — no session, no tools, no history management.
#[tauri::command]
pub async fn simple_chat(payload: SimpleChatPayload) -> Result<String, String> {
    let messages: Vec<Message> = payload
        .messages
        .into_iter()
        .map(|m| Message {
            role: m.role,
            content: vec![ContentBlock::Text { text: m.text }],
        })
        .collect();

    let (content_blocks, _stop) = match payload.provider.as_str() {
        "anthropic" => {
            let client = ClaudeClient::with_model(payload.api_key, &payload.model);
            client
                .send_message(&payload.system_prompt, messages, None)
                .await?
        }
        "openai" | "deepseek" | "google" | "github" => {
            let client =
                OpenAiClient::with_model(payload.api_key, &payload.provider, &payload.model);
            client
                .send_message(&payload.system_prompt, messages, None)
                .await?
        }
        _ => return Err(format!("Unsupported provider: {}", payload.provider)),
    };

    let text = content_blocks
        .iter()
        .filter_map(|b| match b {
            ContentBlock::Text { text } => Some(text.as_str()),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("");

    Ok(text)
}
